spring:
  cloud:
    config:
      uri: http://localhost:8888

google:
  api:
    directions:
      API_KEY: AIzaSyBd2XmXBRgtq2LGbo9HMEUgpfS2ZgXCfpk.
      UNITS: METRIC
      MODE: TRANSIT
      TRANSIT_MODE: TRAIN
      OUTPUT_FORMAT: json
      BASE_URL: https://maps.googleapis.com/maps/api/distancematrix

amazon:
  aws:
    dynamodb:
      REGION: ap-southeast-1
      TABLE_NAME: orang3-dev-table
      ACCESS_KEY_ID: AKIAUFIGDK4UOVXH7V56
      SECRET_ACCESS_KEY: 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