package io.bluextech.ordika.models;
/* Created by limxuanhui on 13/7/23 */

import io.bluextech.ordika.utils.InstantConverter;
import io.bluextech.ordika.utils.MediaConverter;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

import java.time.Instant;

@Setter
@DynamoDbBean
public class User extends BaseDynamoDbItem {

    public static final String PK_PREFIX = "USER#";
    public static final String SK_PREFIX = "#METADATA";
    private String id;
    private String name;
    private String handle;
    private String email;
    private Media avatar;
    private Instant createdAt;
    private Boolean isDeactivated;

    public User() {}

    public User(String id, String name, String handle, String email, Media avatar, Instant createdAt, Boolean isDeactivated) {
        super(PK_PREFIX + id, SK_PREFIX);
        this.id = id;
        this.name = name;
        this.handle = handle;
        this.email = email;
        this.avatar = avatar;
        this.createdAt = createdAt;
        this.isDeactivated = isDeactivated;
    }

    @DynamoDbAttribute(value = "id")
    public String getId() {
        return id;
    }

    @DynamoDbAttribute(value = "name")
    public String getName() {
        return name;
    }

    @DynamoDbAttribute(value = "handle")
    public String getHandle() {
        return handle;
    }

    @DynamoDbAttribute(value = "email")
    public String getEmail() {
        return email;
    }

    @DynamoDbConvertedBy(MediaConverter.class)
    @DynamoDbAttribute(value = "avatar")
    public Media getAvatar() {
        return avatar;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @DynamoDbConvertedBy(InstantConverter.class)
    @DynamoDbAttribute(value = "createdAt")
    public Instant getCreatedAt() {
        return createdAt;
    }

    @DynamoDbAttribute(value = "isDeactivated")
    public Boolean getIsDeactivated() {
        return isDeactivated;
    }

    @Override
    public String toString() {
        return "User{" +
                "PK='" + this.getPK() + '\'' +
                ", SK='" + this.getSK() + '\'' +
                ", id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", handle='" + handle + '\'' +
                ", email='" + email + '\'' +
                ", avatar=" + avatar + '\'' +
                ", createdAt=" + createdAt + '\'' +
                ", isDeactivated=" + isDeactivated +
                '}';
    }

}
