package io.bluextech.ordika.configs;

import io.bluextech.ordika.models.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.DynamoDbClientBuilder;

import java.net.URI;
import java.util.Objects;

@Getter
@Setter
@Configuration
@ConfigurationProperties(prefix = "amazon.aws.dynamodb")
public class DynamoDbConfig {

    private final TableSchema<User> userTableSchema = TableSchema.fromBean(User.class);
    private final TableSchema<BaseMetadata> baseMetadataTableSchema = TableSchema.fromBean(BaseMetadata.class);
    private final TableSchema<FeedMetadata> feedMetadataTableSchema = TableSchema.fromBean(FeedMetadata.class);
    private final TableSchema<FeedItem> feedItemTableSchema = TableSchema.fromBean(FeedItem.class);
    private final TableSchema<TaleMetadata> taleMetadataTableSchema = TableSchema.fromBean(TaleMetadata.class);
    private final TableSchema<Route> routeTableSchema = TableSchema.fromBean(Route.class);
    private final TableSchema<StoryItem> storyItemTableSchema = TableSchema.fromBean(StoryItem.class);
    private final TableSchema<UserDeletionInfo> userDeletionInfoTableSchema = TableSchema.fromBean(UserDeletionInfo.class);
    private final DynamoDbEnhancedClientExtension autogeneratedTimestampExtension = AutoGeneratedTimestampRecordExtension.create();
    @Value("${spring.profiles.active}")
    private String PROFILE;
    private String ENDPOINT;
    private Region REGION;
    private String TABLE_NAME;
    private String ACCESS_KEY_ID;
    private String SECRET_ACCESS_KEY;

    @Bean
    public DynamoDbClient dynamoDbClient() {
        System.out.println("DynamoDbClient " + PROFILE + " bean created");
        AwsBasicCredentials credentials = AwsBasicCredentials.create(ACCESS_KEY_ID, SECRET_ACCESS_KEY);
        DynamoDbClientBuilder builder = DynamoDbClient.builder()
                .region(REGION)
                .credentialsProvider(StaticCredentialsProvider.create(credentials));

        if (Objects.equals(PROFILE, "dev")) {
            builder.endpointOverride(URI.create(ENDPOINT));
        }

        return builder.build();
    }

    @Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient() {
        System.out.println("DynamoDbEnhancedClient bean created");
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient())
                .extensions(autogeneratedTimestampExtension)
                .build();
    }

    @Bean
    public DynamoDbTable<BaseMetadata> baseMetadataTable() {
        System.out.println("DynamoDbTable<BaseMetadata> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, baseMetadataTableSchema);
    }

    @Bean
    public DynamoDbTable<User> userTable() {
        System.out.println("DynamoDbTable<User> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, userTableSchema);
    }

    @Bean
    public DynamoDbTable<FeedMetadata> feedMetadataTable() {
        System.out.println("DynamoDbTable<FeedMetadata> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, feedMetadataTableSchema);
    }

    @Bean
    public DynamoDbTable<FeedItem> feedItemTable() {
        System.out.println("DynamoDbTable<FeedItem> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, feedItemTableSchema);
    }

    @Bean
    public DynamoDbTable<TaleMetadata> taleMetadataTable() {
        System.out.println("DynamoDbTable<TaleMetadata> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, taleMetadataTableSchema);
    }

    @Bean
    public DynamoDbTable<Route> routeTable() {
        System.out.println("DynamoDbTable<Route> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, routeTableSchema);
    }

    @Bean
    public DynamoDbTable<StoryItem> storyItemTable() {
        System.out.println("DynamoDbTable<StoryItem> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, storyItemTableSchema);
    }

    @Bean
    public DynamoDbTable<UserDeletionInfo> userDeletionInfoTable() {
        System.out.println("DynamoDbTable<UserDeletionInfo> bean created");
        return dynamoDbEnhancedClient().table(TABLE_NAME, userDeletionInfoTableSchema);
    }

}